app:
  title: Summer Framework
  version: 1.0.0

# standard structure for datasource, mail, etc:
summer:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.201.100:3306/mytest?characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: root
    max-pool-size: '10'
    min-pool-size: '2'
    time-out: '2000'
    auto-commit: '${AUTO_COMMIT:false}'

# test data types:
other:
  bool-data: true
  int-data: 12345
  hex-data: 0x1a2b3c
  hex-string: "0x1a2b3c"
  deep:
    deep:
      level: level-4
  address: |
    123 Walkman Dr.
    Suite No.456
  list:
    - Apple
    - Orange
    - Pear
# list can include map

convert:
  boolean: true
  byte: 123
  short: 12345
  integer: 1234567
  long: 123456789000
  float: 12345.6789
  double: 123456789.87654321
  localdate: 2023-03-29
  localtime: 20:45:01
  localdatetime: 2023-03-29T20:45:01
  zoneddatetime: 2023-03-29T20:45:01+08:00[Asia/Shanghai]
  duration: P2DT3H4M
  zoneid: Asia/Shanghai

contextT2:
  key: keykeykey
  value: hahahahaha